<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pegjs</string>
	</array>
	<key>name</key>
	<string>PEGjs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#Comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9]+)\s*(=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rule</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=([a-zA-Z0-9]+)\s*(=))</string>
			<key>name</key>
			<string>meta.block.productionset</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#Comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assign</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:([a-zA-Z0-9as]+)(:))?\(?([a-zA-Z0-9]+)\)?</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>keyword.operator.regex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G\^</string>
							<key>name</key>
							<string>keyword.operator.negate</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[wWsSdDhH]</string>
							<key>name</key>
							<string>keyword.other.character_class</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.range</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.range</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.function.range</string>
								</dict>
							</dict>
							<key>match</key>
							<string>((?:\\0[0-7]*)|(?:\\u[0-9A-F]{1,4})|(?:[a-zA-Z0-9]))(-)((?:\\0[0-7]*)|(?:\\u[0-9A-F]{1,4})|(?:[a-zA-Z0-9]))</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\u[0-9a-fA-F]{1,4}</string>
							<key>name</key>
							<string>constant.character.escape.unicode</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;|!</string>
					<key>name</key>
					<string>keyword.operator.predicate</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\*|\?</string>
					<key>name</key>
					<string>keyword.operator.quantifier</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>keyword.operator.productiondivider</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#JavascriptBlock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#SingleQuotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#DoubleQuotedString</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#JavascriptBlock</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>Comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.pegjs</string>
		</dict>
		<key>DoubleQuotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>description</key>
			<string>A double-quoted string.</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{1,4}</string>
					<key>name</key>
					<string>constant.character.escape.unicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<key>JavascriptBlock</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.beginjsblock</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.endjsblock</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#JavascriptBlock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>SingleQuotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>description</key>
			<string>A single-quoted string.</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{1,4}</string>
					<key>name</key>
					<string>constant.character.escape.unicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pegjs</string>
	<key>uuid</key>
	<string>2449a616-1263-49e8-a82b-ae8a604df003</string>
</dict>
</plist>
